export const mockUsers = [
  {
    login: 'agung',
    id: 20548585,
    node_id: 'MDQ6VXNlcjIwNTQ4NTg1',
    avatar_url: 'https://avatars.githubusercontent.com/u/20548585?v=4',
    gravatar_id: '',
    url: 'https://api.github.com/users/agung',
    html_url: 'https://github.com/agung',
    followers_url: 'https://api.github.com/users/agung/followers',
    following_url: 'https://api.github.com/users/agung/following{/other_user}',
    gists_url: 'https://api.github.com/users/agung/gists{/gist_id}',
    starred_url: 'https://api.github.com/users/agung/starred{/owner}{/repo}',
    subscriptions_url: 'https://api.github.com/users/agung/subscriptions',
    organizations_url: 'https://api.github.com/users/agung/orgs',
    repos_url: 'https://api.github.com/users/agung/repos',
    events_url: 'https://api.github.com/users/agung/events{/privacy}',
    received_events_url: 'https://api.github.com/users/agung/received_events',
    type: 'User',
    site_admin: false,
    score: 1.0,
  },
  {
    login: 'agungsetiawan',
    id: 5874815,
    node_id: 'MDQ6VXNlcjU4NzQ4MTU=',
    avatar_url: 'https://avatars.githubusercontent.com/u/5874815?v=4',
    gravatar_id: '',
    url: 'https://api.github.com/users/agungsetiawan',
    html_url: 'https://github.com/agungsetiawan',
    followers_url: 'https://api.github.com/users/agungsetiawan/followers',
    following_url: 'https://api.github.com/users/agungsetiawan/following{/other_user}',
    gists_url: 'https://api.github.com/users/agungsetiawan/gists{/gist_id}',
    starred_url: 'https://api.github.com/users/agungsetiawan/starred{/owner}{/repo}',
    subscriptions_url: 'https://api.github.com/users/agungsetiawan/subscriptions',
    organizations_url: 'https://api.github.com/users/agungsetiawan/orgs',
    repos_url: 'https://api.github.com/users/agungsetiawan/repos',
    events_url: 'https://api.github.com/users/agungsetiawan/events{/privacy}',
    received_events_url: 'https://api.github.com/users/agungsetiawan/received_events',
    type: 'User',
    site_admin: false,
    score: 1.0,
  },
  {
    login: 'agungnursatria',
    id: 15356308,
    node_id: 'MDQ6VXNlcjE1MzU2MzA4',
    avatar_url: 'https://avatars.githubusercontent.com/u/15356308?v=4',
    gravatar_id: '',
    url: 'https://api.github.com/users/agungnursatria',
    html_url: 'https://github.com/agungnursatria',
    followers_url: 'https://api.github.com/users/agungnursatria/followers',
    following_url: 'https://api.github.com/users/agungnursatria/following{/other_user}',
    gists_url: 'https://api.github.com/users/agungnursatria/gists{/gist_id}',
    starred_url: 'https://api.github.com/users/agungnursatria/starred{/owner}{/repo}',
    subscriptions_url: 'https://api.github.com/users/agungnursatria/subscriptions',
    organizations_url: 'https://api.github.com/users/agungnursatria/orgs',
    repos_url: 'https://api.github.com/users/agungnursatria/repos',
    events_url: 'https://api.github.com/users/agungnursatria/events{/privacy}',
    received_events_url: 'https://api.github.com/users/agungnursatria/received_events',
    type: 'User',
    site_admin: false,
    score: 1.0,
  },
  {
    login: 'agungsugiarto',
    id: 10989147,
    node_id: 'MDQ6VXNlcjEwOTg5MTQ3',
    avatar_url: 'https://avatars.githubusercontent.com/u/10989147?v=4',
    gravatar_id: '',
    url: 'https://api.github.com/users/agungsugiarto',
    html_url: 'https://github.com/agungsugiarto',
    followers_url: 'https://api.github.com/users/agungsugiarto/followers',
    following_url: 'https://api.github.com/users/agungsugiarto/following{/other_user}',
    gists_url: 'https://api.github.com/users/agungsugiarto/gists{/gist_id}',
    starred_url: 'https://api.github.com/users/agungsugiarto/starred{/owner}{/repo}',
    subscriptions_url: 'https://api.github.com/users/agungsugiarto/subscriptions',
    organizations_url: 'https://api.github.com/users/agungsugiarto/orgs',
    repos_url: 'https://api.github.com/users/agungsugiarto/repos',
    events_url: 'https://api.github.com/users/agungsugiarto/events{/privacy}',
    received_events_url: 'https://api.github.com/users/agungsugiarto/received_events',
    type: 'User',
    site_admin: false,
    score: 1.0,
  },
  {
    login: 'agungpg',
    id: 35495875,
    node_id: 'MDQ6VXNlcjM1NDk1ODc1',
    avatar_url: 'https://avatars.githubusercontent.com/u/35495875?v=4',
    gravatar_id: '',
    url: 'https://api.github.com/users/agungpg',
    html_url: 'https://github.com/agungpg',
    followers_url: 'https://api.github.com/users/agungpg/followers',
    following_url: 'https://api.github.com/users/agungpg/following{/other_user}',
    gists_url: 'https://api.github.com/users/agungpg/gists{/gist_id}',
    starred_url: 'https://api.github.com/users/agungpg/starred{/owner}{/repo}',
    subscriptions_url: 'https://api.github.com/users/agungpg/subscriptions',
    organizations_url: 'https://api.github.com/users/agungpg/orgs',
    repos_url: 'https://api.github.com/users/agungpg/repos',
    events_url: 'https://api.github.com/users/agungpg/events{/privacy}',
    received_events_url: 'https://api.github.com/users/agungpg/received_events',
    type: 'User',
    site_admin: false,
    score: 1.0,
  },
  {
    login: 'perdana',
    id: 5479951,
    node_id: 'MDQ6VXNlcjU0Nzk5NTE=',
    avatar_url: 'https://avatars.githubusercontent.com/u/5479951?v=4',
    gravatar_id: '',
    url: 'https://api.github.com/users/perdana',
    html_url: 'https://github.com/perdana',
    followers_url: 'https://api.github.com/users/perdana/followers',
    following_url: 'https://api.github.com/users/perdana/following{/other_user}',
    gists_url: 'https://api.github.com/users/perdana/gists{/gist_id}',
    starred_url: 'https://api.github.com/users/perdana/starred{/owner}{/repo}',
    subscriptions_url: 'https://api.github.com/users/perdana/subscriptions',
    organizations_url: 'https://api.github.com/users/perdana/orgs',
    repos_url: 'https://api.github.com/users/perdana/repos',
    events_url: 'https://api.github.com/users/perdana/events{/privacy}',
    received_events_url: 'https://api.github.com/users/perdana/received_events',
    type: 'User',
    site_admin: false,
    score: 1.0,
  },
  {
    login: 'perdanafavo',
    id: 15909985,
    node_id: 'MDQ6VXNlcjE1OTA5OTg1',
    avatar_url: 'https://avatars.githubusercontent.com/u/15909985?v=4',
    gravatar_id: '',
    url: 'https://api.github.com/users/perdanafavo',
    html_url: 'https://github.com/perdanafavo',
    followers_url: 'https://api.github.com/users/perdanafavo/followers',
    following_url: 'https://api.github.com/users/perdanafavo/following{/other_user}',
    gists_url: 'https://api.github.com/users/perdanafavo/gists{/gist_id}',
    starred_url: 'https://api.github.com/users/perdanafavo/starred{/owner}{/repo}',
    subscriptions_url: 'https://api.github.com/users/perdanafavo/subscriptions',
    organizations_url: 'https://api.github.com/users/perdanafavo/orgs',
    repos_url: 'https://api.github.com/users/perdanafavo/repos',
    events_url: 'https://api.github.com/users/perdanafavo/events{/privacy}',
    received_events_url: 'https://api.github.com/users/perdanafavo/received_events',
    type: 'User',
    site_admin: false,
    score: 1.0,
  },
  {
    login: 'perdanaph',
    id: 71249930,
    node_id: 'MDQ6VXNlcjcxMjQ5OTMw',
    avatar_url: 'https://avatars.githubusercontent.com/u/71249930?v=4',
    gravatar_id: '',
    url: 'https://api.github.com/users/perdanaph',
    html_url: 'https://github.com/perdanaph',
    followers_url: 'https://api.github.com/users/perdanaph/followers',
    following_url: 'https://api.github.com/users/perdanaph/following{/other_user}',
    gists_url: 'https://api.github.com/users/perdanaph/gists{/gist_id}',
    starred_url: 'https://api.github.com/users/perdanaph/starred{/owner}{/repo}',
    subscriptions_url: 'https://api.github.com/users/perdanaph/subscriptions',
    organizations_url: 'https://api.github.com/users/perdanaph/orgs',
    repos_url: 'https://api.github.com/users/perdanaph/repos',
    events_url: 'https://api.github.com/users/perdanaph/events{/privacy}',
    received_events_url: 'https://api.github.com/users/perdanaph/received_events',
    type: 'User',
    site_admin: false,
    score: 1.0,
  },
  {
    login: 'rikyperdana',
    id: 11875540,
    node_id: 'MDQ6VXNlcjExODc1NTQw',
    avatar_url: 'https://avatars.githubusercontent.com/u/11875540?v=4',
    gravatar_id: '',
    url: 'https://api.github.com/users/rikyperdana',
    html_url: 'https://github.com/rikyperdana',
    followers_url: 'https://api.github.com/users/rikyperdana/followers',
    following_url: 'https://api.github.com/users/rikyperdana/following{/other_user}',
    gists_url: 'https://api.github.com/users/rikyperdana/gists{/gist_id}',
    starred_url: 'https://api.github.com/users/rikyperdana/starred{/owner}{/repo}',
    subscriptions_url: 'https://api.github.com/users/rikyperdana/subscriptions',
    organizations_url: 'https://api.github.com/users/rikyperdana/orgs',
    repos_url: 'https://api.github.com/users/rikyperdana/repos',
    events_url: 'https://api.github.com/users/rikyperdana/events{/privacy}',
    received_events_url: 'https://api.github.com/users/rikyperdana/received_events',
    type: 'User',
    site_admin: false,
    score: 1.0,
  },
  {
    login: 'gumelar',
    id: 31677991,
    node_id: 'MDQ6VXNlcjMxNjc3OTkx',
    avatar_url: 'https://avatars.githubusercontent.com/u/31677991?v=4',
    gravatar_id: '',
    url: 'https://api.github.com/users/gumelar',
    html_url: 'https://github.com/gumelar',
    followers_url: 'https://api.github.com/users/gumelar/followers',
    following_url: 'https://api.github.com/users/gumelar/following{/other_user}',
    gists_url: 'https://api.github.com/users/gumelar/gists{/gist_id}',
    starred_url: 'https://api.github.com/users/gumelar/starred{/owner}{/repo}',
    subscriptions_url: 'https://api.github.com/users/gumelar/subscriptions',
    organizations_url: 'https://api.github.com/users/gumelar/orgs',
    repos_url: 'https://api.github.com/users/gumelar/repos',
    events_url: 'https://api.github.com/users/gumelar/events{/privacy}',
    received_events_url: 'https://api.github.com/users/gumelar/received_events',
    type: 'User',
    site_admin: false,
    score: 1.0,
  },
  {
    login: 'gumelarme',
    id: 24204176,
    node_id: 'MDQ6VXNlcjI0MjA0MTc2',
    avatar_url: 'https://avatars.githubusercontent.com/u/24204176?v=4',
    gravatar_id: '',
    url: 'https://api.github.com/users/gumelarme',
    html_url: 'https://github.com/gumelarme',
    followers_url: 'https://api.github.com/users/gumelarme/followers',
    following_url: 'https://api.github.com/users/gumelarme/following{/other_user}',
    gists_url: 'https://api.github.com/users/gumelarme/gists{/gist_id}',
    starred_url: 'https://api.github.com/users/gumelarme/starred{/owner}{/repo}',
    subscriptions_url: 'https://api.github.com/users/gumelarme/subscriptions',
    organizations_url: 'https://api.github.com/users/gumelarme/orgs',
    repos_url: 'https://api.github.com/users/gumelarme/repos',
    events_url: 'https://api.github.com/users/gumelarme/events{/privacy}',
    received_events_url: 'https://api.github.com/users/gumelarme/received_events',
    type: 'User',
    site_admin: false,
    score: 1.0,
  },
  {
    login: 'hikmahgumelar',
    id: 4201453,
    node_id: 'MDQ6VXNlcjQyMDE0NTM=',
    avatar_url: 'https://avatars.githubusercontent.com/u/4201453?v=4',
    gravatar_id: '',
    url: 'https://api.github.com/users/hikmahgumelar',
    html_url: 'https://github.com/hikmahgumelar',
    followers_url: 'https://api.github.com/users/hikmahgumelar/followers',
    following_url: 'https://api.github.com/users/hikmahgumelar/following{/other_user}',
    gists_url: 'https://api.github.com/users/hikmahgumelar/gists{/gist_id}',
    starred_url: 'https://api.github.com/users/hikmahgumelar/starred{/owner}{/repo}',
    subscriptions_url: 'https://api.github.com/users/hikmahgumelar/subscriptions',
    organizations_url: 'https://api.github.com/users/hikmahgumelar/orgs',
    repos_url: 'https://api.github.com/users/hikmahgumelar/repos',
    events_url: 'https://api.github.com/users/hikmahgumelar/events{/privacy}',
    received_events_url: 'https://api.github.com/users/hikmahgumelar/received_events',
    type: 'User',
    site_admin: false,
    score: 1.0,
  },
]
